### ISSUE TITLE
Root GRPC responses should be non-null

### ISSUE THREAD

**Issue by jaslong** [hassox/absinthe_proto#8]
In GRPC, it is impossible to send a "nil" root response back. Therefore, we can map these to a non-null object.

Example GRPC service:

```
service Foo {
  method Bar(Request) returns (Response);
}
```

should generate GraphQL schema:

```
type Foo {
  bar(RequestInputObject): Response!
}
```

Note the `Response!` object is non-null.

**Comment by hassox** [comment]
That's not true... The nil response occurs when there is an error for that field.

**Comment by jaslong** [comment]
👍
